import { Car, CarCondition, CarStatus, FuelType, Transmission } from "./types";

export const COMPANY_INFO = {
  name: "Kiambu Autospares Showroom",
  address: "Kiambu Road, Kiambu, Kenya",
  phone: "+254 746 053 175",
  whatsapp: "254746053175", 
  email: "sales@kiambuautospares.co.ke",
  locationCoords: { lat: -1.1717, lng: 36.8327 }, // Approximate Kiambu coords
  openingHours: "Mon - Sat: 8:00 AM - 6:00 PM",
};

export const INITIAL_CARS: Car[] = [
  {
    id: "1",
    make: "Toyota",
    model: "Land Cruiser Prado",
    year: 2020,
    price: 6500000,
    mileage: 45000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Diesel,
    condition: CarCondition.ForeignUsed,
    status: CarStatus.Available,
    images: [
      "https://images.unsplash.com/photo-1594502184342-2b54284d858c?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1626002976865-1d8920155b76?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Immaculate condition Toyota Land Cruiser Prado. TX-L Package. Leather interior, sunroof, low mileage. Ideal for both city driving and off-road adventures.",
    color: "Pearl White",
    engineSize: "2800cc",
    features: ["Sunroof", "Leather Seats", "360 Camera", "Heated Seats", "Alloy Wheels"],
    isFeatured: true,
    createdAt: Date.now(),
  },
  {
    id: "2",
    make: "Mazda",
    model: "CX-5",
    year: 2018,
    price: 2800000,
    mileage: 62000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Diesel,
    condition: CarCondition.ForeignUsed,
    status: CarStatus.Available,
    images: [
      "https://images.unsplash.com/photo-1574874896152-480bc121c26f?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1574875225126-7d6f5f3e9702?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Stylish and efficient Mazda CX-5. This unit comes with the SkyActiv diesel engine offering great fuel economy without compromising on power.",
    color: "Soul Red",
    engineSize: "2200cc",
    features: ["Bose Sound System", "Heads Up Display", "Reverse Camera", "Cruise Control"],
    isFeatured: true,
    createdAt: Date.now(),
  },
  {
    id: "3",
    make: "Mercedes-Benz",
    model: "C-Class C200",
    year: 2017,
    price: 3500000,
    mileage: 58000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Petrol,
    condition: CarCondition.ForeignUsed,
    status: CarStatus.Available,
    images: [
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Experience luxury with this Mercedes Benz C200. AMG Line styling, pristine interior, and smooth drive.",
    color: "Obsidian Black",
    engineSize: "2000cc",
    features: ["AMG Line", "Panoramic Roof", "Memory Seats", "Park Assist"],
    isFeatured: false,
    createdAt: Date.now(),
  },
  {
    id: "4",
    make: "Toyota",
    model: "Vitz",
    year: 2016,
    price: 950000,
    mileage: 85000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Petrol,
    condition: CarCondition.LocallyUsed,
    status: CarStatus.Available,
    images: [
      "https://images.unsplash.com/photo-1583121274602-3e2820c698d9?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Reliable daily runner. Very fuel efficient. Perfect first car.",
    color: "Silver",
    engineSize: "1300cc",
    features: ["Keyless Entry", "Push Start", "DVD Player"],
    isFeatured: false,
    createdAt: Date.now(),
  },
   {
    id: "5",
    make: "Subaru",
    model: "Forester",
    year: 2019,
    price: 3200000,
    mileage: 35000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Petrol,
    condition: CarCondition.ForeignUsed,
    status: CarStatus.Sold,
    images: [
      "https://images.unsplash.com/photo-1630650231815-a567e2a46613?auto=format&fit=crop&w=800&q=80",
    ],
    description: "Subaru Forester XT. Turbo charged. Eyesight technology.",
    color: "White",
    engineSize: "2000cc",
    features: ["Eyesight", "X-Mode", "Electric Seats", "Turbo"],
    isFeatured: true,
    createdAt: Date.now(),
  },
  // --- NEW ADDITIONS ---
  {
    id: "6",
    make: "Mitsubishi",
    model: "Pajero Sport",
    year: 2021,
    price: 5800000,
    mileage: 25000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Diesel,
    condition: CarCondition.ForeignUsed,
    status: CarStatus.Available,
    images: ["https://images.unsplash.com/photo-1628277613967-6bc52471b6ae?auto=format&fit=crop&w=800&q=80"],
    description: "Rugged yet refined. The Pajero Sport combines off-road capability with luxury comfort.",
    color: "Deep Bronze",
    engineSize: "2400cc",
    features: ["7 Seater", "Leather Interior", "Off-road Mode", "Paddle Shifters"],
    isFeatured: true,
    createdAt: Date.now(),
  },
  {
    id: "7",
    make: "Honda",
    model: "CR-V",
    year: 2019,
    price: 3800000,
    mileage: 42000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Petrol,
    condition: CarCondition.ForeignUsed,
    status: CarStatus.Available,
    images: ["https://images.unsplash.com/photo-1518987048-93e29699e79a?auto=format&fit=crop&w=800&q=80"],
    description: "The perfect family SUV. Spacious, reliable, and economical.",
    color: "Lunar Silver",
    engineSize: "1500cc Turbo",
    features: ["Sunroof", "Lane Watch", "Electric Tailgate", "Apple CarPlay"],
    isFeatured: false,
    createdAt: Date.now(),
  },
  {
    id: "8",
    make: "Volkswagen",
    model: "Tiguan",
    year: 2018,
    price: 3400000,
    mileage: 55000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Petrol,
    condition: CarCondition.ForeignUsed,
    status: CarStatus.Available,
    images: ["https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80"],
    description: "German engineering at its finest. R-Line package with digital cockpit.",
    color: "Pure White",
    engineSize: "2000cc",
    features: ["Digital Cockpit", "R-Line Body Kit", "Panoramic Roof", "Heated Seats"],
    isFeatured: true,
    createdAt: Date.now(),
  },
  {
    id: "9",
    make: "BMW",
    model: "X5",
    year: 2017,
    price: 6200000,
    mileage: 68000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Diesel,
    condition: CarCondition.ForeignUsed,
    status: CarStatus.Available,
    images: ["https://images.unsplash.com/photo-1556189250-72ba954e96b5?auto=format&fit=crop&w=800&q=80"],
    description: "The ultimate driving machine. XDrive30d M-Sport package.",
    color: "Carbon Black",
    engineSize: "3000cc",
    features: ["M-Sport Package", "Harman Kardon Audio", "Head-up Display", "Gesture Control"],
    isFeatured: true,
    createdAt: Date.now(),
  },
  {
    id: "10",
    make: "Nissan",
    model: "X-Trail",
    year: 2020,
    price: 3100000,
    mileage: 38000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Hybrid,
    condition: CarCondition.ForeignUsed,
    status: CarStatus.Available,
    images: ["https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=800&q=80"],
    description: "Efficient hybrid SUV with 7 seats. Great for city and long distance.",
    color: "Garnet Red",
    engineSize: "2000cc Hybrid",
    features: ["7 Seater", "Hybrid System", "360 Camera", "Emergency Braking"],
    isFeatured: false,
    createdAt: Date.now(),
  },
  {
    id: "11",
    make: "Toyota",
    model: "Harrier",
    year: 2018,
    price: 3900000,
    mileage: 45000,
    transmission: Transmission.Automatic,
    fuelType: FuelType.Petrol,
    condition: CarCondition.ForeignUsed,
    status: CarStatus.Available,
    images: ["https://images.unsplash.com/photo-1621007947382-bb3c3968e3bb?auto=format&fit=crop&w=800&q=80"],
    description: "Premium crossover SUV. Elegance meets performance.",
    color: "Black",
    engineSize: "2000cc",
    features: ["Leather/Alcantara Seats", "Power Tailgate", "Safety Sense", "LED Headlights"],
    isFeatured: true,
    createdAt: Date.now(),
  }
];

export const CAR_MAKES = ["Toyota", "Mazda", "Nissan", "Subaru", "Mercedes-Benz", "BMW", "Audi", "Land Rover", "Honda", "Volkswagen", "Mitsubishi"];